### ISSUE TITLE
Wrong comparison in libopenkey.c

### ISSUE THREAD

**Issue by kr15h** [henryk/libopenkey#2]
Throws error while compiling on Mac OS X

```
libopenkey.c:1070:134: error: comparison of unsigned expression < 0 is always false
      [-Werror,-Wtautological-compare]
```

Proposed fix (tested, works):

```
if(gcry_kdf_derive(pw, pw_length, GCRY_KDF_PBKDF2, OPENKEY_PBKDF_PRF, data, data_length, iterations, pbkdf2_key_length, pbkdf2_key) != 0) {
        goto abort;
}
```

Check `gcry_kdf_derive` documentation: http://lists.gnupg.org/pipermail/gcrypt-devel/2011-March/001747.html (Returns positive error code on failure, 0 on success)

**Comment by henryk** [comment]
Ahh, dang. I now checked with clang as a compiler and luckily there are no additional instances of the same problem.
